namespace Fable.BluePrint.Icons


open Fable.Core
open Fable.Helpers.React
open Fable.Helpers.React.Props
open Fable.Import.React
open Fable.Core.JsInterop

[<StringEnum>]
type IconNames =
    | Add
    | [<CompiledName("add-column-left")>] AddColumnLeft
    | [<CompiledName("add-column-right")>] AddColumnRight
    | [<CompiledName("add-row-bottom")>] AddRowBottom
    | [<CompiledName("add-row-top")>] AddRowTop
    | [<CompiledName("add-to-artifact")>] AddToArtiface
    | [<CompiledName("add-to-folder")>] AddToFolder
    | [<CompiledName("airplane")>] Airplane
    | [<CompiledName("align-center")>] AlignCenter
    | [<CompiledName("align-justify")>] AlignJustify
    | [<CompiledName("align-left")>] AlignLeft
    | [<CompiledName("align-right")>] AlignRight
    | [<CompiledName("alignment-bottom")>] AlignmentBottom
    | [<CompiledName("alignment-horizontal-center")>] AlignmentHorizontalCenter
    | [<CompiledName("alignment-left")>] AlignmentLeft
    | [<CompiledName("alignment-right")>] AlignmentRight
    | [<CompiledName("alignment-top")>] AlignmentTop
    | [<CompiledName("alignment-vertical-center")>] AlignmentVerticalCenter
    | [<CompiledName("annotation")>] Annotation
    | [<CompiledName("application")>] Application
    | [<CompiledName("applications")>] Applications
    | [<CompiledName("arrow-bottom-left")>] ArrowBottomLeft
    | [<CompiledName("arrow-bottom-right")>] ArrowBottomRight
    | [<CompiledName("arrow-down")>] ArrowDown
    | [<CompiledName("arrow-left")>] ArrowLeft
    | [<CompiledName("arrow-right")>] ArrowRight
    | [<CompiledName("arrow-top-left")>] ArrowTopLeft
    | [<CompiledName("arrow-top-right")>] ArrowTopRight
    | [<CompiledName("arrow-up")>] ArrowUp
    | [<CompiledName("arrows-horizontal")>] ArrowsHorizontal
    | [<CompiledName("arrows-vertical")>] ArrowsVertical
    | [<CompiledName("asterisk")>] Asterisk
    | [<CompiledName("automatic-updates")>] AutomaticUpdates
    | [<CompiledName("badge")>] Badge
    | [<CompiledName("ban-circle")>] BanCircle
    | [<CompiledName("bank-account")>] BankAccount
    | [<CompiledName("barcode")>] Barcode
    | [<CompiledName("blank")>] Blank
    | [<CompiledName("blocked-person")>] BlockedPerson
    | [<CompiledName("bold")>] Bold
    | [<CompiledName("book")>] Book
    | [<CompiledName("bookmark")>] Bookmark
    | [<CompiledName("box")>] Box
    | [<CompiledName("briefcase")>] BriefCase
    | [<CompiledName("build")>] Build
    | [<CompiledName("calculator")>] Calculator
    | [<CompiledName("calendar")>] Calendar
    | [<CompiledName("camera")>] Camera
    | [<CompiledName("caret-down")>] CaretDown
    | [<CompiledName("caret-left")>] CaretLeft
    | [<CompiledName("caret-right")>] CaretRight
    | [<CompiledName("caret-up")>] CaretUp
    | [<CompiledName("cell-tower")>] CellTower
    | [<CompiledName("changes")>] Changes
    | [<CompiledName("chart")>] Chart
    | [<CompiledName("chat")>] Chat
    | [<CompiledName("chevron-backward")>] ChevronBackward
    | [<CompiledName("chevron-down")>] ChevronDown
    | [<CompiledName("chevron-forward")>] ChevronForward
    | [<CompiledName("chevron-left")>] ChevronLeft
    | [<CompiledName("chevron-right")>] ChevronRight
    | [<CompiledName("chevron-up")>] ChevronUp
    | [<CompiledName("circle")>] Circle
    | [<CompiledName("circle-arrow-down")>] CircleArrowDown
    | [<CompiledName("circle-arrow-left")>] CircleArrowLeft
    | [<CompiledName("circle-arrow-right")>] CircleArrowRight
    | [<CompiledName("circle-arrow-up")>] CircleArrowUp
    | [<CompiledName("citation")>] Citation
    | [<CompiledName("clean")>] Clean
    | [<CompiledName("clipboard")>] Clipboard
    | [<CompiledName("cloud")>] Cloud
    | [<CompiledName("cloud-download")>] CloudDownload
    | [<CompiledName("cloud-upload")>] CloudUpload
    | [<CompiledName("code")>] Code
    | [<CompiledName("code-block")>] CodeBlock
    | [<CompiledName("cog")>] Cog
    | [<CompiledName("collapse-all")>] CollapseAll
    | [<CompiledName("column-layout")>] ColumnLayout
    | [<CompiledName("comment")>] Comment
    | [<CompiledName("comparison")>] Comparision
    | [<CompiledName("compass")>] Compass
    | [<CompiledName("compressed")>] Compressed
    | [<CompiledName("confirm")>] Confirm
    | [<CompiledName("console")>] Console
    | [<CompiledName("contrast")>] Contrast
    | [<CompiledName("control")>] Control
    | [<CompiledName("credit-card")>] CreditCard
    | [<CompiledName("cross")>] Cross
    | [<CompiledName("crown")>] Crown
    | [<CompiledName("curved-range-chart")>] CurvedRangeChart
    | [<CompiledName("cut")>] Cut
    | [<CompiledName("dashboard")>] Dashboard
    | [<CompiledName("database")>] Database
    | [<CompiledName("delete")>] Delete
    | [<CompiledName("delta")>] Delta
    | [<CompiledName("derive-column")>] DeriveColumn
    | [<CompiledName("desktop")>] Desktop
    | [<CompiledName("diagram-tree")>] DiagramTree
    | [<CompiledName("direction-left")>] DirectionLeft
    | [<CompiledName("direction-right")>] DirectionRight
    | [<CompiledName("disable")>] Disable
    | [<CompiledName("document")>] Document
    | [<CompiledName("document-open")>] DoumentOpen
    | [<CompiledName("document-share")>] DocumentShare
    | [<CompiledName("dollar")>] Dollar
    | [<CompiledName("dot")>] Dot
    | [<CompiledName("double-caret-horizontal")>] DobuleCaretHorizontal
    | [<CompiledName("double-caret-vertical")>] DoubleCaretVertical
    | [<CompiledName("double-chevron-down")>] DoubleChevronDown
    | [<CompiledName("double-chevron-left")>] DoubleChevronLeft
    | [<CompiledName("double-chevron-right")>] DoubleChevronRight
    | [<CompiledName("double-chevron-up")>] DoubleChevronUp
    | [<CompiledName("doughnut-chart")>] DoughnuChart
    | [<CompiledName("download")>] Download
    | [<CompiledName("drag-handle-horizontal")>] DragHandleHorizontal
    | [<CompiledName("drag-handle-vertical")>] DragHandleVertical
    | [<CompiledName("draw")>] Draw
    | [<CompiledName("drive-time")>] DriveTime
    | [<CompiledName("duplicate")>] Duplicate
    | [<CompiledName("edit")>] Edit
    | [<CompiledName("eject")>] Eject
    | [<CompiledName("endorsed")>] Endorsed
    | [<CompiledName("envelope")>] Envelope
    | [<CompiledName("eraser")>] Eraser
    | [<CompiledName("error")>] Error
    | [<CompiledName("euro")>] Euro
    | [<CompiledName("exchange")>] Exchange
    | [<CompiledName("exclude-row")>] ExcludeRow
    | [<CompiledName("expand-all")>] ExpandAll
    | [<CompiledName("export")>] Export
    | [<CompiledName("eye-off")>] EyeOff
    | [<CompiledName("eye-on")>] EyeOn
    | [<CompiledName("eye-open")>] EyeOpen
    | [<CompiledName("fast-backward")>] FastBackward
    | [<CompiledName("fast-forward")>] FastForward
    | [<CompiledName("feed")>] Feed
    | [<CompiledName("feed-subscribed")>] FeedSubscribed
    | [<CompiledName("film")>] Film
    | [<CompiledName("filter")>] Filter
    | [<CompiledName("filter-keep")>] FilterKeep
    | [<CompiledName("filter-list")>] FilterList
    | [<CompiledName("filter-remove")>] FilterRemove
    | [<CompiledName("flag")>] Flag
    | [<CompiledName("flame")>] Flame
    | [<CompiledName("flash")>] Flash
    | [<CompiledName("floppy-disk")>] FloppyDisk
    | [<CompiledName("flow-branch")>] FlowBranch
    | [<CompiledName("flow-end")>] FlowEnd
    | [<CompiledName("flow-linear")>] FlowLinear
    | [<CompiledName("flow-review")>] FlowReview
    | [<CompiledName("flow-review-branch")>] FlowReviewBranch
    | [<CompiledName("flows")>] Flows
    | [<CompiledName("folder-close")>] FolderClose
    | [<CompiledName("folder-new")>] FolderNew
    | [<CompiledName("folder-open")>] FolderOpen
    | [<CompiledName("folder-shared")>] FolderShared
    | [<CompiledName("folder-shared-open")>] FolderSharedOpen
    | [<CompiledName("follower")>] Follower
    | [<CompiledName("following")>] Following
    | [<CompiledName("font")>] Font
    | [<CompiledName("fork")>] Fork
    | [<CompiledName("form")>] Form
    | [<CompiledName("full-circle")>] FullCircle
    | [<CompiledName("full-stacked-chart")>] FullStackedChart
    | [<CompiledName("fullscreen")>] FullScreen
    | [<CompiledName("function")>] Function
    | [<CompiledName("gantt-chart")>] GanttChart
    | [<CompiledName("geolocation")>] Geolocation
    | [<CompiledName("geosearch")>] Geosearch
    | [<CompiledName("git-branch")>] GitBranch
    | [<CompiledName("git-commit")>] GitCommit
    | [<CompiledName("git-merge")>] GitMerge
    | [<CompiledName("git-new-branch")>] GitNewBranch
    | [<CompiledName("git-pull")>] GitPull
    | [<CompiledName("git-push")>] GitPush
    | [<CompiledName("git-repo")>] GitRepo
    | [<CompiledName("glass")>] Glass
    | [<CompiledName("globe")>] Globe
    | [<CompiledName("globe-network")>] GlobeNetwork
    | [<CompiledName("graph")>] Graph
    | [<CompiledName("graph-remove")>] GraphRemove
    | [<CompiledName("grid")>] Grid
    | [<CompiledName("grid-view")>] GridView
    | [<CompiledName("group-objects")>] GroupObjects
    | [<CompiledName("grouped-bar-chart")>] GroupedBarChart
    | [<CompiledName("hand")>] Hand
    | [<CompiledName("hand-down")>] HandDown
    | [<CompiledName("hand-left")>] HandLeft
    | [<CompiledName("hand-right")>] HandRight
    | [<CompiledName("hand-up")>] HandUp
    | [<CompiledName("header")>] Header
    | [<CompiledName("header-one")>] HeaderOne
    | [<CompiledName("header-two")>] HeaderTwo
    | [<CompiledName("headset")>] Headset
    | [<CompiledName("heart")>] Heart
    | [<CompiledName("heart-broken")>] HeartBroken
    | [<CompiledName("heat-grid")>] HeatGrid
    | [<CompiledName("heatmap")>] Heatmap
    | [<CompiledName("help")>] Help
    | [<CompiledName("helper-management")>] HelperManagement
    | [<CompiledName("highlight")>] Highlight
    | [<CompiledName("history")>] History
    | [<CompiledName("home")>] Home
    | [<CompiledName("horizontal-bar-chart")>] HorizontalBarChart
    | [<CompiledName("horizontal-bar-chart-asc")>] HorizontalBarChartAsc
    | [<CompiledName("horizontal-bar-chart-desc")>] HorizontalBarChartDesc
    | [<CompiledName("horizontal-distribution")>] HorizontalDistribution
    | [<CompiledName("id-number")>] IdNumber
    | [<CompiledName("image-rotate-left")>] ImageRotateLeft
    | [<CompiledName("image-rotate-right")>] ImageRotateRight
    | [<CompiledName("import")>] Import
    | [<CompiledName("inbox")>] Inbox
    | [<CompiledName("info-sign")>] InfoSign
    | [<CompiledName("inner-join")>] InnerJoin
    | [<CompiledName("insert")>] Insert
    | [<CompiledName("intersection")>] Intersection
    | [<CompiledName("ip-address")>] IpAddress
    | [<CompiledName("issue")>] Issue
    | [<CompiledName("issue-closed")>] IssueClosed
    | [<CompiledName("issue-new")>] IssueNew
    | [<CompiledName("italic")>] Italic
    | [<CompiledName("join-table")>] JoinTable
    | [<CompiledName("key")>] Key
    | [<CompiledName("key-backspace")>] KeyBackspace
    | [<CompiledName("key-command")>] KeyCommand
    | [<CompiledName("key-control")>] KeyControl
    | [<CompiledName("key-delete")>] KeyDelete
    | [<CompiledName("key-enter")>] KeyEnter
    | [<CompiledName("key-escape")>] KeyEscape
    | [<CompiledName("key-option")>] KeyOption
    | [<CompiledName("key-shift")>] KeyShift
    | [<CompiledName("key-tab")>] KeyTab
    | [<CompiledName("known-vehicle")>] KnownVehicle
    | [<CompiledName("label")>] Label
    | [<CompiledName("layer")>] Layer
    | [<CompiledName("layers")>] Layers
    | [<CompiledName("layout")>] Layout
    | [<CompiledName("layout-auto")>] LayoutAuto
    | [<CompiledName("layout-balloon")>] LayoutBalloon
    | [<CompiledName("layout-circle")>] LayoutCircle
    | [<CompiledName("layout-grid")>] LayoutGrid
    | [<CompiledName("layout-group-by")>] LayoutGroupBy
    | [<CompiledName("layout-hierarchy")>] LayoutHierarchy
    | [<CompiledName("layout-linear")>] LayoutLinear
    | [<CompiledName("layout-skew-grid")>] LayoutSkewGrid
    | [<CompiledName("layout-sorted-clusters")>] LayoutSortedClusters
    | [<CompiledName("left-join")>] LeftJoin
    | [<CompiledName("lightbulb")>] LightBlub
    | [<CompiledName("link")>] Link
    | [<CompiledName("list")>] List
    | [<CompiledName("list-columns")>] ListColumns
    | [<CompiledName("list-detail-view")>] ListDetailView
    | [<CompiledName("locate")>] Locate
    | [<CompiledName("lock")>] Lock
    | [<CompiledName("log-in")>] LogIn
    | [<CompiledName("log-out")>] LogOut
    | [<CompiledName("manual")>] Manual
    | [<CompiledName("manually-entered-data")>] ManuallyEnteredData
    | [<CompiledName("map")>] Map
    | [<CompiledName("map-create")>] MapCreate
    | [<CompiledName("map-marker")>] MapMarker
    | [<CompiledName("maximize")>] Maximize
    | [<CompiledName("media")>] Media
    | [<CompiledName("menu")>] Menu
    | [<CompiledName("menu-closed")>] MenuClosed
    | [<CompiledName("menu-open")>] MenuOpen
    | [<CompiledName("merge-columns")>] MergeColumns
    | [<CompiledName("merge-links")>] MergeLinks
    | [<CompiledName("minimize")>] Minimize
    | [<CompiledName("minus")>] Minus
    | [<CompiledName("mobile-phone")>] MobilePhone
    | [<CompiledName("mobile-video")>] MobileVideo
    | [<CompiledName("moon")>] Moon
    | [<CompiledName("more")>] More
    | [<CompiledName("mountain")>] Mountain
    | [<CompiledName("move")>] Move
    | [<CompiledName("mugshot")>] Mugshot
    | [<CompiledName("multi-select")>] MultiSelect
    | [<CompiledName("music")>] Music
    | [<CompiledName("new-grid-item")>] NewGridItem
    | [<CompiledName("new-link")>] NewLink
    | [<CompiledName("new-object")>] NewObject
    | [<CompiledName("new-person")>] NewPerson
    | [<CompiledName("new-prescription")>] NewPrescription
    | [<CompiledName("new-text-box")>] NewTextBox
    | [<CompiledName("ninja")>] Ninja
    | [<CompiledName("notifications")>] Notifications
    | [<CompiledName("notifications-updated")>] NotificationsUpdated
    | [<CompiledName("numbered-list")>] NumberedList
    | [<CompiledName("numerical")>] Numerical
    | [<CompiledName("office")>] Office
    | [<CompiledName("offline")>] Offline
    | [<CompiledName("oil-field")>] OilField
    | [<CompiledName("one-column")>] OneColumn
    | [<CompiledName("outdated")>] Outdated
    | [<CompiledName("page-layout")>] PageLayout
    | [<CompiledName("panel-stats")>] PanelStats
    | [<CompiledName("panel-table")>] PanelTable
    | [<CompiledName("paperclip")>] Paperclip
    | [<CompiledName("paragraph")>] Paragraph
    | [<CompiledName("path")>] Path
    | [<CompiledName("path-search")>] PathSearch
    | [<CompiledName("pause")>] Pause
    | [<CompiledName("people")>] People
    | [<CompiledName("percentage")>] Percentage
    | [<CompiledName("person")>] Person
    | [<CompiledName("phone")>] Phone
    | [<CompiledName("pie-chart")>] PieChart
    | [<CompiledName("pin")>] Pin
    | [<CompiledName("pivot")>] Pivot
    | [<CompiledName("pivot-table")>] PivotTable
    | [<CompiledName("play")>] Play
    | [<CompiledName("plus")>] Plus
    | [<CompiledName("polygon-filter")>] PolygonFilter
    | [<CompiledName("power")>] Power
    | [<CompiledName("predictive-analysis")>] PredictiveAnalysis
    | [<CompiledName("prescription")>] Prescription
    | [<CompiledName("presentation")>] Presentation
    | [<CompiledName("print")>] Print
    | [<CompiledName("projects")>] Projects
    | [<CompiledName("properties")>] Properties
    | [<CompiledName("property")>] Property
    | [<CompiledName("publish-function")>] PublishFunction
    | [<CompiledName("pulse")>] Pulse
    | [<CompiledName("random")>] Random
    | [<CompiledName("record")>] Record
    | [<CompiledName("redo")>] Redo
    | [<CompiledName("refresh")>] Refresh
    | [<CompiledName("regression-chart")>] RegressionChart
    | [<CompiledName("remove")>] Remove
    | [<CompiledName("remove-column")>] RemoveColumn
    | [<CompiledName("remove-column-left")>] RemoveColumnLeft
    | [<CompiledName("remove-column-right")>] RemoveColumnRight
    | [<CompiledName("remove-row-bottom")>] RemoveRowBottom
    | [<CompiledName("remove-row-top")>] RemoveRowTop
    | [<CompiledName("repeat")>] Repeat
    | [<CompiledName("resolve")>] Resolve
    | [<CompiledName("rig")>] Rig
    | [<CompiledName("right-join")>] RightJoin
    | [<CompiledName("ring")>] Ring
    | [<CompiledName("rotate-document")>] RotateDocument
    | [<CompiledName("rotate-page")>] RotatePage
    | [<CompiledName("satellite")>] Satellite
    | [<CompiledName("saved")>] Saved
    | [<CompiledName("scatter-plot")>] ScatterPlot
    | [<CompiledName("search")>] Search
    | [<CompiledName("search-around")>] SearchAround
    | [<CompiledName("search-template")>] SearchTemplate
    | [<CompiledName("search-text")>] SearchText
    | [<CompiledName("segmented-control")>] SegmentedControl
    | [<CompiledName("select")>] Select
    | [<CompiledName("selection")>] Selection
    | [<CompiledName("send-to")>] SendTo
    | [<CompiledName("send-to-graph")>] SendToGraph
    | [<CompiledName("send-to-map")>] SendToMap
    | [<CompiledName("series-add")>] SeriesAdd
    | [<CompiledName("series-configuration")>] SeriesConfiguration
    | [<CompiledName("series-derived")>] SeriesDerived
    | [<CompiledName("series-filtered")>] SeriesFiltered
    | [<CompiledName("series-search")>] SeriesSearch
    | [<CompiledName("settings")>] Settings
    | [<CompiledName("share")>] Share
    | [<CompiledName("shield")>] Shield
    | [<CompiledName("shop")>] Shop
    | [<CompiledName("shopping-cart")>] ShoppingCart
    | [<CompiledName("sim-card")>] SimCard
    | [<CompiledName("slash")>] Slash
    | [<CompiledName("small-cross")>] SmallCross
    | [<CompiledName("small-minus")>] SmallMinus
    | [<CompiledName("small-plus")>] SmallPlus
    | [<CompiledName("small-tick")>] SmallTick
    | [<CompiledName("snowflake")>] Snowflake
    | [<CompiledName("social-media")>] SocialMedia
    | [<CompiledName("sort")>] Sort
    | [<CompiledName("sort-alphabetical")>] SortAlphabetical
    | [<CompiledName("sort-alphabetical-desc")>] SortAlphabeticalDesc
    | [<CompiledName("sort-asc")>] SortAsc
    | [<CompiledName("sort-desc")>] SortDesc
    | [<CompiledName("sort-numerical")>] SortNumerical
    | [<CompiledName("sort-numerical-desc")>] SortNumericalDesc
    | [<CompiledName("split-columns")>] SplitColumns
    | [<CompiledName("square")>] Square
    | [<CompiledName("stacked-chart")>] StackedChart
    | [<CompiledName("star")>] Star
    | [<CompiledName("star-empty")>] StarEmpty
    | [<CompiledName("step-backward")>] StepBackward
    | [<CompiledName("step-chart")>] StepChart
    | [<CompiledName("step-forward")>] StepForward
    | [<CompiledName("stop")>] Stop
    | [<CompiledName("strikethrough")>] Strikethrough
    | [<CompiledName("style")>] Style
    | [<CompiledName("swap-horizontal")>] SwapHorizontal
    | [<CompiledName("swap-vertical")>] SwapVertical
    | [<CompiledName("symbol-circle")>] SymbolCircle
    | [<CompiledName("symbol-cross")>] SymbolCross
    | [<CompiledName("symbol-diamond")>] SymbolDiamond
    | [<CompiledName("symbol-square")>] SymbolSquare
    | [<CompiledName("symbol-triangle-down")>] SymbolTriangleDown
    | [<CompiledName("symbol-triangle-up")>] SymbolTriangleUp
    | [<CompiledName("tag")>] Tag
    | [<CompiledName("take-action")>] TakeAction
    | [<CompiledName("taxi")>] Taxi
    | [<CompiledName("text-highlight")>] TextHighlight
    | [<CompiledName("th")>] Th
    | [<CompiledName("th-derived")>] ThDerived
    | [<CompiledName("th-list")>] ThList
    | [<CompiledName("thumbs-down")>] ThumbsDown
    | [<CompiledName("thumbs-up")>] ThumbsUp
    | [<CompiledName("tick")>] Tick
    | [<CompiledName("tick-circle")>] TickCircle
    | [<CompiledName("time")>] Time
    | [<CompiledName("timeline-area-chart")>] TimelineAreaChart
    | [<CompiledName("timeline-bar-chart")>] TimelineBarChart
    | [<CompiledName("timeline-events")>] TimelineEvents
    | [<CompiledName("timeline-line-chart")>] TimelineLineChart
    | [<CompiledName("tint")>] Tint
    | [<CompiledName("torch")>] Torch
    | [<CompiledName("train")>] Train
    | [<CompiledName("translate")>] Translate
    | [<CompiledName("trash")>] Trash
    | [<CompiledName("tree")>] Tree
    | [<CompiledName("trending-down")>] TrendingDown
    | [<CompiledName("trending-up")>] TrendingUp
    | [<CompiledName("two-columns")>] TwoColumns
    | [<CompiledName("underline")>] Underline
    | [<CompiledName("undo")>] Undo
    | [<CompiledName("ungroup-objects")>] UngroupObjects
    | [<CompiledName("unknown-vehicle")>] UnknownVehicle
    | [<CompiledName("unlock")>] Unlock
    | [<CompiledName("unpin")>] Unpin
    | [<CompiledName("unresolve")>] Unresolve
    | [<CompiledName("updated")>] Updated
    | [<CompiledName("upload")>] Upload
    | [<CompiledName("user")>] User
    | [<CompiledName("variable")>] Veriable
    | [<CompiledName("vertical-bar-chart-asc")>] VerticalBarChartAsc
    | [<CompiledName("vertical-bar-chart-desc")>] VerticalBarChartDesc
    | [<CompiledName("vertical-distribution")>] VerticalDistribution
    | [<CompiledName("video")>] Video
    | [<CompiledName("volume-down")>] VolumeDown
    | [<CompiledName("volume-off")>] VolumeOff
    | [<CompiledName("volume-up")>] VolumeUp
    | [<CompiledName("walk")>] Walk
    | [<CompiledName("warning-sign")>] WarningSign
    | [<CompiledName("waterfall-chart")>] WaterfallChart
    | [<CompiledName("widget")>] Widget
    | [<CompiledName("widget-button")>] WidgetButton
    | [<CompiledName("widget-footer")>] WidgetFooter
    | [<CompiledName("widget-header")>] WidgetHeader
    | [<CompiledName("wrench")>] Wrench
    | [<CompiledName("zoom-in")>] ZoomIn
    | [<CompiledName("zoom-out")>] ZoomOut
    | [<CompiledName("zoom-to-fit")>] ZoomToFit
